### ISSUE TITLE
in converter.php & config.php file_get_contents() returns empty

### ISSUE THREAD

**Issue by RafaAguilar** [owncloud/documents#498]
Hello friends,

I have an issue trying to enable MS Support for this app, but after certain issues, i got this messages:

```
{"reqId":"b12c705512f38a4f75acb940f2271e00","remoteAddr":"10.192.251.83","app":"documents","message":"Conversion test failed. Raw output:","level":2,"time":"2015-06-19T18:19:39+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/documents\/ajax\/admin.php"}
```

I'm running __OC 8.0.2__ on a __Centos 6.6 x86_64__ and __LibreOffice 4.0.4__.

I run the command  generated from `config.php` replacing the target file and it runs fine, i print out the content of `$input` and it returns _empty_ in the following snippet:

```php
// owncloud/apps/documents/lib/config.php
                $targetFilter = 'odt:writer8';
                $targetExtension = 'odt';
                $input = file_get_contents(dirname(__DIR__) . self::TEST_DOC_PATH);
                shell_exec('echo Contenido > /tmp/rafa.log');
                shell_exec('echo ' . dirname(__DIR__) . self::TEST_DOC_PATH . ' >> /tmp/rafa.log');
                shell_exec('echo ' . file_get_contents(dirname(__DIR__) . self::TEST_DOC_PATH) . ' >> /tmp/rafa.l$
                $infile = \OCP\Files::tmpFile();
                $outdir = \OCP\Files::tmpFolder();
                $outfile = $outdir . '/' . basename($infile) . '.' . $targetExtension;
                $cmd = Helper::findOpenOffice();
```

in the `converter.php` file is also empty.

I Turn off SELinux and nothing, i run a simple script that read .doc content as an Apache user and it runs fine.

Someone can point me where is my misstake?

**Comment by VicDeo** [comment]
mmm. Possibly `shell_exec` is in the list of disabled functions

**Comment by VicDeo** [comment]
@RafaAguilar can you check if shell_exec works at all on this host?
Just ceate file test.php, put it to webroot and open it from browser. Here is a content:
<?php shell_exec('echo Contenido'); ?>

**Comment by RafaAguilar** [comment]
That error was showed to me on an dev enviroment on a former employment, however i tell a colleague to test it, sorry if we answer late.

**Comment by freddyc26** [comment]
@VicDeo hello. Perform the test and the file opens correctly from the browser, shell_exec is working.

**Comment by VicDeo** [comment]
@freddyc26 and 'Contenido' is displayed on the page?

**Comment by freddyc26** [comment]
@VicDeo yeah, is shown.

**Comment by VicDeo** [comment]
@freddyc26 please post `'preview_libreoffice_path'` value from your `config.php`

**Comment by ggujabidze** [comment]
Hello VicDeo. As I see freddyc26 didn't unswered you yet, so as soon as I also have exactly the same problem, I'll provide you the value:  'preview_libreoffice_path' => '/usr/bin/libreoffice',

In addition I'll say, that I have CentOS 7 x64 Server and ownCloud Server v.8.1.3, PHP Version 5.4.16, MariaDB Server v.5.5.44, Apache Server v.2.4.6, disable_functions parameter has no value, I can run shell_exec() function. I can successfully open any .odt file in browser and edit it, but when i try to open .docx files, I'm getting the that huge error:

Exception: {"Exception":"RuntimeException","Message":"Empty conversion output","Code":0,"Trace":"#0 \/var\/www\/html\/owncloud\/apps\/documents\/lib\/filter\/office.php(69): OCA\\Documents\\Converter::convert('PK??????????!??...', 'odt:writer8', 'odt')\n#1 [internal function]: OCA\\Documents\\Filter\\Office->read(Array)\n#2 \/var\/www\/html\/owncloud\/apps\/documents\/lib\/filter.php(35): call_user_func(Array, Array)\n#3 \/var\/www\/html\/owncloud\/apps\/documents\/lib\/genesis.php(60): OCA\\Documents\\Filter::read('PK??????????!??...', 'application\/vnd...')\n#4 \/var\/www\/html\/owncloud\/apps\/documents\/controller\/documentcontroller.php(108): OCA\\Documents\\Genesis->__construct(Object(OCA\\Documents\\File))\n#5 [internal function]: OCA\\Documents\\Controller\\DocumentController->download('\/Documents\/fing...')\n#6 \/var\/www\/html\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(159): call_user_func_array(Array, Array)\n#7 \/var\/www\/html\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(89): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Documents\\Controller\\DocumentController), 'download')\n#8 \/var\/www\/html\/owncloud\/lib\/private\/appframework\/app.php(108): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Documents\\Controller\\DocumentController), 'download')\n#9 \/var\/www\/html\/owncloud\/lib\/private\/appframework\/routing\/routeactionhandler.php(45): OC\\AppFramework\\App::main('DocumentControl...', 'download', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#10 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#11 \/var\/www\/html\/owncloud\/lib\/private\/route\/router.php(274): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#12 \/var\/www\/html\/owncloud\/lib\/base.php(874): OC\\Route\\Router->match('\/apps\/documents...')\n#13 \/var\/www\/html\/owncloud\/index.php(40): OC::handleRequest()\n#14 {main}","File":"\/var\/www\/html\/owncloud\/apps\/documents\/lib\/converter.php","Line":26}
![owncloud log screen](https://cloud.githubusercontent.com/assets/14991833/10302745/c96647de-6c1f-11e5-8039-1e30368d8836.JPG)

**Comment by VicDeo** [comment]
@ggujabidze  can you put this docx file as `test.docx` in any dir at your server and run the following command in this dir:
`/usr/bin/libreoffice  --headless --convert-to odt:writer8 --outdir .  --writer test.docx`
as your webserver user, not root.

**Comment by ggujabidze** [comment]
@VicDeo Hi and sorry for late reply.
Unfortunately I can't run the command with webserver user credentials, as I'm running CentOS server and the service user for web server - apache is disabled and you can not neither log in with it, nor run any command explicitly via that user  :(

But, anyways, when I'm trying to run that command with root account, I'm still getting error. It's strange, but libreoffice is trying to reach X server and as I have no GUI on my server, it returns an error message:

/usr/lib64/libreoffice/program/soffice.bin X11 error: Can't open display:
   Set DISPLAY environment variable, use -display option
   or check permissions of your X-Server

P.S. How are you manage to highlight that text and change the text font? I don't see any text manipulating panel, while writing the post :(

**Comment by VicDeo** [comment]
@ggujabidze 
a) Do you have `libreoffice-headless` package installed on this server?
b) Use backticks

**Comment by ggujabidze** [comment]
Oh, my bad, I've install all basic libreoffice packages and thought that headless package would be included into them and didn't check  :( It's really shame, I've installed it and now I confirm that Documents App v.0.10.2 is able to open and edit M$ Office files on Server v.8.1.3 and working perfectly  :) 

So, I think that this bug might be closed.

Thanks a lot for your assistance!
