### ISSUE TITLE
Document Collaboration error

### ISSUE THREAD

**Issue by david2012brooke** [owncloud/documents#551]
### Steps to reproduce
1.From the Documents view, select shared or not shared document.
2.
3.

### Expected behaviour
Once the document is selected, it should open in edit mode.

### Actual behaviour
The screen refreshes and the original Documents screen is presented with an error message:
"Failed to load this document. Please check if it can be opened with an external odt editor. This might also mean it has been unshared or deleted recently."

### Server configuration
Gentoo linux

**Web server:**
Lighttpd

**Database:**
SQLite3

**PHP version:**
5.6

**ownCloud version:** (see ownCloud admin page)
8.1.1

**Updated from an older ownCloud or fresh install:**
No, this is a new installtion.

**List of activated apps:**
Your instructions for listing the apps doesn't work in Gentoo.
"If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder"

Documents 0.10.2

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'oca170ed1jji',
  'passwordsalt' => 'x',
  'secret' => 'x',
  'trusted_domains' => 
  array (
    0 => '192.168.107.100',
  ),
  'datadirectory' => '/media/sdd1/owncloud/data',
  'overwrite.cli.url' => 'http://localhost/owncloud',
  'dbtype' => 'sqlite3',
  'version' => '8.1.1.3',
  'logtimezone' => 'UTC',
  'installed' => true,
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
  'loglevel' => 0,
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
NO

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
NO

### Client configuration
**Browser:**
Google Chrome

**Operating system:**
Gentoo linux

#### Web server error log (repeat these two lines only)
2015-09-21 10:48:06: (mod_fastcgi.c.2521) FastCGI-stderr: PHP message: PHP Deprecated:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0
2015-09-21 10:48:06: (mod_fastcgi.c.2521) FastCGI-stderr: PHP message: PHP Warning:  Cannot modify header information - headers already sent in Unknown on line 0

#### ownCloud log (data/owncloud.log)
{"reqId":"zWX9IzKNWHUEkejAtxUH","remoteAddr":"::ffff:192.168.107.100","app":"base","message":"Exception: {\"Exception\":\"ErrorException\",\"Message\":\"session_start(): Cannot send session cache limiter - headers already sent\",\"Code\":0,\"Trace\":\"#0 [internal function]: OC\\\\Session\\\\Internal->trapError(2, 'session_start()...', '\\\/var\\\/www\\\/localh...', 38, Array)\\n#1 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/session\\\/internal.php(38): session_start()\\n#2 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(454): OC\\\\Session\\\\Internal->__construct('oca170ed1jji')\\n#3 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(594): OC::initSession()\\n#4 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(1121): OC::init()\\n#5 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/index.php(38): require_once('\\\/var\\\/www\\\/localh...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/session\\\/internal.php\",\"Line\":104}","level":4,"time":"2015-09-20T22:40:51+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/documents\/ajax\/session\/joinasuser\/51"}
{"reqId":"zWX9IzKNWHUEkejAtxUH","remoteAddr":"::ffff:192.168.107.100","app":"index","message":"Exception: {\"Exception\":\"ErrorException\",\"Message\":\"Cannot modify header information - headers already sent\",\"Code\":0,\"Trace\":\"#0 [internal function]: OC\\\\Session\\\\Internal->trapError(2, 'Cannot modify h...', '\\\/var\\\/www\\\/localh...', 103, Array)\\n#1 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/response.php(103): header('HTTP\\\/1.1 500 In...')\\n#2 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(460): OC_Response::setStatus(500)\\n#3 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(594): OC::initSession()\\n#4 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(1121): OC::init()\\n#5 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/index.php(38): require_once('\\\/var\\\/www\\\/localh...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/session\\\/internal.php\",\"Line\":104}","level":4,"time":"2015-09-20T22:40:51+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/documents\/ajax\/session\/joinasuser\/51"}
{"reqId":"zWX9IzKNWHUEkejAtxUH","remoteAddr":"::ffff:192.168.107.100","app":"PHP","message":"ErrorException: Cannot modify header information - headers already sent at \/var\/www\/localhost\/htdocs\/owncloud\/lib\/private\/session\/internal.php#104","level":3,"time":"2015-09-20T22:40:51+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/documents\/ajax\/session\/joinasuser\/51"}
{"reqId":"zWX9IzKNWHUEkejAtxUH","remoteAddr":"::ffff:192.168.107.100","app":"PHP","message":"Cannot modify header information - headers already sent at Unknown#0","level":3,"time":"2015-09-20T22:40:51+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/documents\/ajax\/session\/joinasuser\/51"}

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by david2012brooke** [comment]
Any progress?

**Comment by VicDeo** [comment]
@david2012brooke
```
{"reqId":"zWX9IzKNWHUEkejAtxUH","remoteAddr":"::ffff:192.168.107.100","app":"index","message":"Exception: {\"Exception\":\"ErrorException\",\"Message\":\"Cannot modify header information - headers already sent\",\"Code\":0,\"Trace\":\"#0 [internal function]: OC\\Session\\Internal->trapError(2, 'Cannot modify h...', '\\/var\\/www\\/localh...', 103, Array)\n#1 
```
is abnormal and not related to the Documents app. You need to find the script that starts premature output.

the complete message looks like this: Cannot modify header information - headers already sent by (output started at `/some/file.php:#LINE_NUMBER`) in /some/file.php on line 23
Grep your web server error log for `output started at` pattern and post the output here.

**Comment by ToggoStar** [comment]
I had the same issue - going back to PHP version 5.5 solved it. This is the same issue as #623.
