### ISSUE TITLE
Issue with reading .ods files Owncloud 8.2

### ISSUE THREAD

**Issue by team4music** [owncloud/documents#582]
Hey there, 
I'm running Documents on Owncloud 8.2 on DEB Nginx and php FPM
everytime as i try to open .ods files i see this here and nothing else happens
http://bild-speichern.de/Vm.jpg

Within the Logfile i can read

```
Exception: {"Exception":"Exception","Message":"\/files\/Sonstiges\/testfile3.ods is application\/vnd.oasis.opendocument.spreadsheet and is not supported by Documents app","Code":0,"Trace":"#0 \/var\/www\/clients\/client1\/web33\/team\/apps\/documents\/lib\/file.php(62): OCA\\Documents\\File->initViews()\n#1 \/var\/www\/clients\/client1\/web33\/team\/apps\/documents\/controller\/documentcontroller.php(125): OCA\\Documents\\File->__construct(418)\n#2 [internal function]: OCA\\Documents\\Controller\\DocumentController->download('\/Sonstiges\/test...')\n#3 \/var\/www\/clients\/client1\/web33\/team\/lib\/private\/appframework\/http\/dispatcher.php(159): call_user_func_array(Array, Array)\n#4 \/var\/www\/clients\/client1\/web33\/team\/lib\/private\/appframework\/http\/dispatcher.php(89): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Documents\\Controller\\DocumentController), 'download')\n#5 \/var\/www\/clients\/client1\/web33\/team\/lib\/private\/appframework\/app.php(108): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Documents\\Controller\\DocumentController), 'download')\n#6 \/var\/www\/clients\/client1\/web33\/team\/lib\/private\/appframework\/routing\/routeactionhandler.php(45): OC\\AppFramework\\App::main('DocumentControl...', 'download', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#7 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#8 \/var\/www\/clients\/client1\/web33\/team\/lib\/private\/route\/router.php(282): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#9 \/var\/www\/clients\/client1\/web33\/team\/lib\/base.php(831): OC\\Route\\Router->match('\/apps\/documents...')\n#10 \/var\/www\/clients\/client1\/web33\/team\/index.php(39): OC::handleRequest()\n#11 {main}","File":"\/var\/www\/clients\/client1\/web33\/team\/apps\/documents\/lib\/file.php","Line":193} 
```

Also if i click on Edit within the Filebrowser nothing happens and i get redirected to the file overview.

**Comment by RealRancor** [comment]
Confirmed by @brrrrrrrt in https://github.com/owncloud/documents/issues/580

**Comment by RealRancor** [comment]
Might be fixed with https://github.com/owncloud/documents/pull/592 ?

**Comment by beccon4** [comment]
I have the same isssues 
- opening spreadsheeds ods and impress presentations odp "loading" forever - but another log entry such as: 
>{\"Exception\":\"Exception\",\"Message\":\"\\\/files\\\/meinedatei.ods is application\\\/vnd.oasis.opendocument.spreadsheet and is not supported by Documents app ... }

- trying to edit an odt file jumps back the file app as reported by team4music. I can open and it within documents though

- new: i cannot open xlsx files - they'll just download

**Comment by RealRancor** [comment]
@beccon4 1 and 3 are probably related to this issue. Nr. 2 to the already reported issue here: https://github.com/owncloud/documents/issues/564

Both are known so you probably just need to have some patience until someone is looking at this issues.

**Comment by 0ki** [comment]
ods, odp and odg files gave the error.
https://github.com/owncloud/documents/pull/592 fixes ods and odp files.

odg now displays an empty page.

**Comment by averi** [comment]
Any luck to have [the above patch](https://github.com/tpayen/documents/commit/c76acf24393387da1e444450761e7049b1f4b8e9) included on the next stable release update? (stable releases channel)

**Comment by RealRancor** [comment]
@averi This documents app is not shipped with oC core so it can't be shipped via the stable releases channel. The fix itself was alredy merged with https://github.com/owncloud/documents/pull/592 so some one just needs to release a new version of the documents app at the appstore.

**Comment by VicDeo** [comment]
@RealRancor one who needs to release a new version should merge some backports first ;)
